resources:
- repo: self
queue:
  name: home-automation

variables:
  imageName: 'geertvdc/dsmr-reader-docker-arm'

steps:
- script: |
    version="$(grep -w 'ENV DSMR_READER_VERSION' Dockerfile | grep -o '[0-9]*\.[0-9]*\.[0-9]*')"
    docker build -f Dockerfile -t "$(imageName):${version}-alpine" .
    docker push "$(imageName):${version}-alpine"
  displayName: 'Docker Build & Push'
